web:
  restart: always
  build: ./web/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
    - ipfs:ipfs
  env_file: env
  volumes:
    - ./web:/data/web
    - ./ipfs/export:/mnt
    - ./ipfs/ssh:/root/.ssh
  command: /usr/bin/gunicorn sljweb.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./backups/postgresql:/backup
  env_file:
    - env
  ports:
    - "12345:5432"
  expose:
    - "5432"

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"

ipfs:
  restart: always
  image: ipfs/go-ipfs:k
  volumes:
    - ./ipfs/export:/export
    - ./ipfs/data:/data/ipfs
    - ./ipfs/ssh:/root/.ssh
  ports:
    - "4001:4001"
    - "127.0.0.1:8080:8080"
    - "127.0.0.1:5001:5001"
  expose:
    - "22"

data:
  restart: always
  image: alpine
  volumes:
    - /var/lib/postgresql
  command: "true"

